package controller

import (
	"context"
	"path/filepath"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	policyv1 "k8s.io/api/policy/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/envtest"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"

	pulsev1alpha1 "github.com/PulseSRE/pulse-operator/api/v1alpha1"
)

var (
	testCtx    context.Context
	testCancel context.CancelFunc
	testEnv    *envtest.Environment
	k8sClient  client.Client
	testScheme *runtime.Scheme
	reconciler *AgentReconciler
)

// TestControllers is the ginkgo entry point registered with the standard testing runner.
func TestControllers(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "AgentReconciler Suite")
}

var _ = BeforeSuite(func() {
	logf.SetLogger(zap.New(zap.WriteTo(GinkgoWriter), zap.UseDevMode(true)))
	testCtx, testCancel = context.WithCancel(context.Background())

	testEnv = &envtest.Environment{
		// CRD YAMLs are generated by controller-gen into config/crd/bases.
		// testdata/crds holds minimal permissive stand-ins for OpenShift/Prometheus
		// Operator APIs (Route, OAuthClient, ServiceMonitor, PrometheusRule) that
		// envtest's vanilla kube-apiserver doesn't serve natively — without these,
		// every test that touches those GVKs would silently skip instead of run.
		CRDDirectoryPaths: []string{
			filepath.Join("..", "..", "config", "crd", "bases"),
			filepath.Join("testdata", "crds"),
		},
		// true, not false: with false a missing CRD directory starts envtest
		// anyway, the Route/OAuthClient/ServiceMonitor GVKs are simply absent,
		// and every test touching them skips itself. That turns a broken test
		// environment into a green board. Fail at suite start instead.
		ErrorIfCRDPathMissing: true,
	}

	cfg, err := testEnv.Start()
	Expect(err).NotTo(HaveOccurred())
	Expect(cfg).NotTo(BeNil())

	testScheme = runtime.NewScheme()
	Expect(corev1.AddToScheme(testScheme)).To(Succeed())
	Expect(appsv1.AddToScheme(testScheme)).To(Succeed())
	Expect(rbacv1.AddToScheme(testScheme)).To(Succeed())
	Expect(networkingv1.AddToScheme(testScheme)).To(Succeed())
	Expect(policyv1.AddToScheme(testScheme)).To(Succeed())
	Expect(pulsev1alpha1.AddToScheme(testScheme)).To(Succeed())

	k8sClient, err = client.New(cfg, client.Options{Scheme: testScheme})
	Expect(err).NotTo(HaveOccurred())
	Expect(k8sClient).NotTo(BeNil())

	reconciler = &AgentReconciler{
		Client: k8sClient,
		Scheme: testScheme,
	}

	_ = ctrl.Log // ensure logger initialised
})

var _ = AfterSuite(func() {
	testCancel()
	Expect(testEnv.Stop()).To(Succeed())
})
