---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulse-operator-manager-role
rules:
- apiGroups: [""]
  resources: [configmaps, persistentvolumeclaims, secrets, serviceaccounts, services,
    pods, "pods/log", nodes, endpoints, limitranges, resourcequotas, "services/proxy",
    namespaces, events]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [apps]
  resources: [deployments, statefulsets, replicasets, daemonsets]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [autoscaling]
  resources: [horizontalpodautoscalers]
  verbs: [get, list, watch]
- apiGroups: [batch]
  resources: [jobs, cronjobs]
  verbs: [get, list, watch]
- apiGroups: [discovery.k8s.io]
  resources: [endpointslices]
  verbs: [get, list, watch]
- apiGroups: [metrics.k8s.io]
  resources: [nodes, pods]
  verbs: [get, list]
- apiGroups: [storage.k8s.io]
  resources: [storageclasses]
  verbs: [get, list, watch]
- apiGroups: [networking.k8s.io]
  resources: [ingresses, networkpolicies]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [policy]
  resources: [poddisruptionbudgets]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [rbac.authorization.k8s.io]
  resources: [clusterroles, clusterrolebindings, roles, rolebindings]
  verbs: [bind, create, delete, escalate, get, list, patch, update, watch]
- apiGroups: [monitoring.coreos.com]
  resources: [servicemonitors, prometheusrules]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [route.openshift.io]
  resources: [routes]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [oauth.openshift.io]
  resources: [oauthclients]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [config.openshift.io]
  resources: [ingresses]
  verbs: [get, list, watch]
- apiGroups: [image.openshift.io]
  resources: [imagestreams]
  verbs: [get, list, watch]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [create, get, list, patch, update, watch]
- apiGroups: [pulse.ai]
  resources: [openshiftpulses, "openshiftpulses/status", "openshiftpulses/finalizers"]
  verbs: [create, delete, get, list, patch, update, watch]
