//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeyConfig) DeepCopyInto(out *APIKeyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyConfig.
func (in *APIKeyConfig) DeepCopy() *APIKeyConfig {
	if in == nil {
		return nil
	}
	out := new(APIKeyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfig) DeepCopyInto(out *AgentConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.MCP = in.MCP
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfig.
func (in *AgentConfig) DeepCopy() *AgentConfig {
	if in == nil {
		return nil
	}
	out := new(AgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPConfig) DeepCopyInto(out *MCPConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPConfig.
func (in *MCPConfig) DeepCopy() *MCPConfig {
	if in == nil {
		return nil
	}
	out := new(MCPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfig.
func (in *MonitoringConfig) DeepCopy() *MonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftPulse) DeepCopyInto(out *OpenShiftPulse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftPulse.
func (in *OpenShiftPulse) DeepCopy() *OpenShiftPulse {
	if in == nil {
		return nil
	}
	out := new(OpenShiftPulse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftPulse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftPulseList) DeepCopyInto(out *OpenShiftPulseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenShiftPulse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftPulseList.
func (in *OpenShiftPulseList) DeepCopy() *OpenShiftPulseList {
	if in == nil {
		return nil
	}
	out := new(OpenShiftPulseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftPulseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftPulseSpec) DeepCopyInto(out *OpenShiftPulseSpec) {
	*out = *in
	if in.VertexAI != nil {
		in, out := &in.VertexAI, &out.VertexAI
		*out = new(VertexAIConfig)
		**out = **in
	}
	if in.AnthropicAPIKey != nil {
		in, out := &in.AnthropicAPIKey, &out.AnthropicAPIKey
		*out = new(APIKeyConfig)
		**out = **in
	}
	in.Agent.DeepCopyInto(&out.Agent)
	in.UI.DeepCopyInto(&out.UI)
	out.Database = in.Database
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	in.Temporal.DeepCopyInto(&out.Temporal)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftPulseSpec.
func (in *OpenShiftPulseSpec) DeepCopy() *OpenShiftPulseSpec {
	if in == nil {
		return nil
	}
	out := new(OpenShiftPulseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftPulseStatus) DeepCopyInto(out *OpenShiftPulseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpgradeStartedAt != nil {
		in, out := &in.UpgradeStartedAt, &out.UpgradeStartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftPulseStatus.
func (in *OpenShiftPulseStatus) DeepCopy() *OpenShiftPulseStatus {
	if in == nil {
		return nil
	}
	out := new(OpenShiftPulseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalConfig) DeepCopyInto(out *TemporalConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalConfig.
func (in *TemporalConfig) DeepCopy() *TemporalConfig {
	if in == nil {
		return nil
	}
	out := new(TemporalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIConfig) DeepCopyInto(out *UIConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIConfig.
func (in *UIConfig) DeepCopy() *UIConfig {
	if in == nil {
		return nil
	}
	out := new(UIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VertexAIConfig) DeepCopyInto(out *VertexAIConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VertexAIConfig.
func (in *VertexAIConfig) DeepCopy() *VertexAIConfig {
	if in == nil {
		return nil
	}
	out := new(VertexAIConfig)
	in.DeepCopyInto(out)
	return out
}
